name: Nix Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  nix-build-linux:
    name: Build with Nix (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-23.11
          extra_nix_config: |
            experimental-features = nix-command flakes
            sandbox = false

      - name: Install cachix
        uses: cachix/cachix-action@v12
        with:
          name: nixpkgs
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Show Nix version
        run: nix --version

      - name: Build with Nix
        run: nix build .#default --show-trace

      - name: Test binaries
        run: |
          ./result/bin/port-kill --help
          ./result/bin/port-kill-console --help

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: port-kill-linux
          path: result/bin/*

  nix-build-macos:
    name: Build with Nix (macOS)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-23.11
          extra_nix_config: |
            experimental-features = nix-command flakes
            sandbox = false

      - name: Install cachix
        uses: cachix/cachix-action@v12
        with:
          name: nixpkgs
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Show Nix version
        run: nix --version

      - name: Build with Nix
        run: nix build .#default --show-trace

      - name: Test binaries
        run: |
          ./result/bin/port-kill --help
          ./result/bin/port-kill-console --help

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: port-kill-macos
          path: result/bin/*