name: Build and Release

on:
  release:
    types: [published]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build macOS binary
        run: |
          chmod +x ./build-macos.sh
          ./build-macos.sh

      - name: Upload macOS binary
        uses: actions/upload-artifact@v4
        with:
          name: port-kill-macos
          path: |
            target/release/port-kill
            target/release/port-kill-console
          retention-days: 30

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libatk1.0-dev libgdk-pixbuf2.0-dev libgtk-3-dev libxdo-dev pkg-config

      - name: Build Linux binary
        run: |
          chmod +x ./build-linux.sh
          ./build-linux.sh

      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: port-kill-linux
          path: |
            target/release/port-kill
            target/release/port-kill-console
          retention-days: 30

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Windows binary
        run: |
          # Use the existing build script instead of duplicating logic
          ./build-windows.bat

      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: port-kill-windows
          path: |
            target/release/port-kill.exe
            target/release/port-kill-console.exe
          retention-days: 30

  create-release:
    needs: [build-macos, build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create release assets
        run: |
          # Create directories for each platform
          mkdir -p release-assets
          
          # macOS assets
          cd artifacts/port-kill-macos
          tar -czf ../../release-assets/port-kill-macos.tar.gz port-kill port-kill-console
          cd ../..
          
          # Linux assets
          cd artifacts/port-kill-linux
          tar -czf ../../release-assets/port-kill-linux.tar.gz port-kill port-kill-console
          cd ../..
          
          # Windows assets
          cd artifacts/port-kill-windows
          zip -r ../../release-assets/port-kill-windows.zip port-kill.exe port-kill-console.exe
          cd ../..
          
          # Create individual binary files for direct download
          cp artifacts/port-kill-macos/port-kill release-assets/port-kill-macos
          cp artifacts/port-kill-macos/port-kill-console release-assets/port-kill-console-macos
          cp artifacts/port-kill-linux/port-kill release-assets/port-kill-linux
          cp artifacts/port-kill-linux/port-kill-console release-assets/port-kill-console-linux
          cp artifacts/port-kill-windows/port-kill.exe release-assets/port-kill-windows.exe
          cp artifacts/port-kill-windows/port-kill-console.exe release-assets/port-kill-console-windows.exe
          
          # Make binaries executable
          chmod +x release-assets/port-kill-macos
          chmod +x release-assets/port-kill-console-macos
          chmod +x release-assets/port-kill-linux
          chmod +x release-assets/port-kill-console-linux

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release-assets/port-kill-macos.tar.gz
          asset_name: port-kill-macos.tar.gz
          asset_content_type: application/gzip

      - name: Upload macOS console binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release-assets/port-kill-console-macos
          asset_name: port-kill-console-macos
          asset_content_type: application/octet-stream

      - name: Upload Linux binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release-assets/port-kill-linux.tar.gz
          asset_name: port-kill-linux.tar.gz
          asset_content_type: application/gzip

      - name: Upload Linux console binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release-assets/port-kill-console-linux
          asset_name: port-kill-console-linux
          asset_content_type: application/octet-stream

      - name: Upload Windows binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release-assets/port-kill-windows.zip
          asset_name: port-kill-windows.zip
          asset_content_type: application/zip

      - name: Upload Windows console binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release-assets/port-kill-console-windows.exe
          asset_name: port-kill-console-windows.exe
          asset_content_type: application/octet-stream

      - name: Upload macOS binary (direct)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release-assets/port-kill-macos
          asset_name: port-kill-macos
          asset_content_type: application/octet-stream

      - name: Upload Linux binary (direct)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release-assets/port-kill-linux
          asset_name: port-kill-linux
          asset_content_type: application/octet-stream

      - name: Upload Windows binary (direct)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release-assets/port-kill-windows.exe
          asset_name: port-kill-windows.exe
          asset_content_type: application/octet-stream
